### ISSUE TITLE
arch(arm64_32) is not recognized by swiftc

### ISSUE THREAD

**Issue by varungandhi-apple** [apple/swift-atomics#19]
This line emits a warning:
https://github.com/apple/swift-atomics/blob/df9f811f19a852fa7b78af9cffa8ec447eaeb40a/Sources/Atomics/AtomicStrongReference.swift#L82

```
warning: unknown architecture for build configuration 'arch'
```

According to TSPL, only `i386`, `x86_64`, `arm` and `arm64` are supported.

**Comment by lorentey** [comment]
This enables the package to be used in watchOS apps built with Xcode. (https://bugs.swift.org/browse/SR-13709)

We could replace the `arch(arm64_32)` condition with `os(watchOS)`, but that feels even further away from the thing this is intended to query. Perhaps we can replace the compile-time condition with a runtime check for `Int.bitWidth`.

**Comment by varungandhi-apple** [comment]
Until the compiler side problem is fixed (it seems like a big task from a cursory look), would it make sense to add a comment here with the JIRA number and having the `os(watchOS)` with an explanation that ideally it ought to be `arch(arm64_32)`? If we do that, then folks trying to compile the package don't have to see the warning, at the cost of some non-ideal configuration in the implementation.

**Comment by lorentey** [comment]
My worry is that such workarounds have a tendency of remaining in the codebase long after they're obsoleted by platform/compiler changes.

However, `if Int.bitWidth == 32` seems like an excellent way to get rid of the warning while also preventing any and all future platform issues -- and also greatly improving readability. (The package is already heavily relying on constant folding/dead code elimination, so this is unlikely to be a big deal.)

**Comment by jckarter** [comment]
`armv7k` and `arm64_32` slices of watchOS code have to be bitcode-compatible, so can we actually have behavior that diverges based on compiler target here?

**Comment by varungandhi-apple** [comment]
> However, if Int.bitWidth == 32 seems like an excellent way to get rid of the warning while also preventing any and all future platform issues -- and also greatly improving readability. (The package is already heavily relying on constant folding/dead code elimination, so this is unlikely to be a big deal.)

That is also a good workaround IMO, certainly clearer than the `os(watchOS)`. 👍🏼

**Comment by lorentey** [comment]
@jckarter AFAICT all of the approaches (including the original code) maintain that invariant. Do you see an issue I'm not seeing?

**Comment by jckarter** [comment]
I was responding more to Varun's comment about why `arch(arm64_32)` might not be supported, since conditional compilation that leads to divergent armv7k/arm64_32 behavior isn't really feasible for watchOS.

**Comment by lorentey** [comment]
`arch(arm64_32)` is supported by the toolchains distributed in Xcode, and because it's disjunct from `arch(arm)`, Swift packages that support watchOS sometimes need to mention it -- otherwise they'd have divergent behavior between watch platforms.

The swift.org toolchains don't support compiling code for `arm64_32`. This is fine, as watchOS apps are expected to get compiled with the proprietary toolchains. However, the open-source compilers also emit a pointless diagnostic whenever they come across `arch(arm64_32)`, which makes the life of cross-platform package developers a tiny bit more difficult. It doesn't help that the diagnostic triggers even in inactive code:

```swift
func foo() {
  #if false
  #if arch(arm64_32) // warning: Unknown architecture for build configuration 'arch'. Did you mean 'arm64'?
  print("Hello, arm64_32")
  #endif
  #endif
}
```
