### ISSUE TITLE
`ManagedAtomicLazyReference` leaks memory

### ISSUE THREAD

**Issue by nkbelov** [apple/swift-atomics#66]
`ManagedAtomicLazyReference` leaks its contents.

### Information

- **Package version:** `.upToNextMajor(from: "1.0.0")`
- **Platform version:** macOS 12.6
- **Swift version:** 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

### Checklist

- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] I've searched for [existing reports](https://github.com/apple/swift-atomics/issues) of the same issue.

### Steps to Reproduce

```swift

final class Box<T: Sendable> {
    let value: T
    
    init(value: T) {
        self.value = value
    }
    
    deinit {
        print("BOX DEINIT")
    }
}

final class Item {

    private let test = ManagedAtomicLazyReference<Box<Int>>()

    init() {
        test.storeIfNilThenLoad(Box(value: 12345))
    }
    
    deinit {
        print("ITEM DEINIT")
    }
}

func test() {
    let _ = Item()
}
```

```swift
//`main.swift`:
test()

// prints "ITEM DEINIT" only
```

### Expected behavior
"`BOX DEINIT`" and "`ITEM DEINIT`"  get printed.

### Actual behavior
Only "`ITEM DEINIT`" gets printed.

**Comment by lorentey** [comment]
Good catch! `ManagedAtomicLazyReference` fails to call `dispose` on its stored value.
