### ISSUE TITLE
Compiling a dependent package using branch: "main" fails due to symlinks

### ISSUE THREAD

**Issue by rvsrvs** [apple/swift-atomics#98]
Building a package which depends on:

`.package(url: "https://github.com/apple/swift-atomics.git", branch: "main")`

with Xcode 15 RC1 fails with the message:

```
the package manifest at '/Package@swift-5.8.swift' cannot be accessed (InternalError(description: "Internal error. Please file a bug at https://github.com/apple/swift-package-manager/issues with this info. symlinks not supported")) in https://github.com/apple/swift-atomics.git
```

Changing the symlinks for `Package@swift-5.7.swift` and `Package@swift-5.8.swift` to be actual files by copying the linked file into place resolves the problem.

### Information

- **Package version:**  Current main on 13-Sep-2023
- **Platform version:** MacOS Sonoma RC1
- **Swift version:** swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) Target: arm64-apple-macosx14.0

### Checklist

- [x ] If possible, I've reproduced the issue using the `main` branch of this package.
- [ x] I've searched for [existing reports](https://github.com/apple/swift-atomics/issues) of the same issue.

### Steps to Reproduce
create a new package with the depdenency shown above.  It will fail with that message

### Expected behavior
It should compile successfully

### Actual behavior
See above.

**Comment by lorentey** [comment]
Good catch! We'll probably want to duplicate the file contents then. (Weird that this proved an issue on macOS, of all platforms...)

**Comment by ktoso** [comment]
Let's do a naive simple fix for now to avoid symlinks.

Perhaps this can be cleaned up a bit so multiple copies would not be necessary? But to unblock development for folks here's a simple patch: https://github.com/apple/swift-atomics/pull/100
